import { Router } from "express";
import userController from "../../controllers/userController/userController.js";
import { validateDataMiddleware } from "../../middleware/validateMiddleware.js";
import { userLoginSchema, userRegistrationSchema, verifyUserSchema } from "../../validations/zod.js";
export const authRouter: Router = Router();
authRouter.route(`/register`).post(validateDataMiddleware(userRegistrationSchema), userController.register);
authRouter.route(`/verify-account`).get(userController.verifyAccount);
authRouter.route(`/login`).post(validateDataMiddleware(userLoginSchema), userController.login);
authRouter.route("/refresh-access-token").get(userController.refreshAccessToken);
authRouter.route("/resend-OTP").post(validateDataMiddleware(verifyUserSchema), userController.resendOTPLink);
authRouter.route("/resend-OTP").post(validateDataMiddleware(verifyUserSchema), userController.resendOTPLink);
